// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: expansion.proto

#include "expansion.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace valhalla {
PROTOBUF_CONSTEXPR Expansion_Geometry::Expansion_Geometry(
    ::_pbi::ConstantInitialized)
  : coords_()
  , _coords_cached_byte_size_(0){}
struct Expansion_GeometryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Expansion_GeometryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Expansion_GeometryDefaultTypeInternal() {}
  union {
    Expansion_Geometry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Expansion_GeometryDefaultTypeInternal _Expansion_Geometry_default_instance_;
PROTOBUF_CONSTEXPR Expansion::Expansion(
    ::_pbi::ConstantInitialized)
  : costs_()
  , _costs_cached_byte_size_(0)
  , durations_()
  , _durations_cached_byte_size_(0)
  , distances_()
  , _distances_cached_byte_size_(0)
  , edge_status_()
  , _edge_status_cached_byte_size_(0)
  , edge_id_()
  , _edge_id_cached_byte_size_(0)
  , pred_edge_id_()
  , _pred_edge_id_cached_byte_size_(0)
  , geometries_()
  , expansion_type_()
  , _expansion_type_cached_byte_size_(0){}
struct ExpansionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExpansionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExpansionDefaultTypeInternal() {}
  union {
    Expansion _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExpansionDefaultTypeInternal _Expansion_default_instance_;
}  // namespace valhalla
namespace valhalla {
bool Expansion_EdgeStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> Expansion_EdgeStatus_strings[3] = {};

static const char Expansion_EdgeStatus_names[] =
  "connected"
  "reached"
  "settled";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry Expansion_EdgeStatus_entries[] = {
  { {Expansion_EdgeStatus_names + 0, 9}, 0 },
  { {Expansion_EdgeStatus_names + 9, 7}, 2 },
  { {Expansion_EdgeStatus_names + 16, 7}, 1 },
};

static const int Expansion_EdgeStatus_entries_by_number[] = {
  0, // 0 -> connected
  2, // 1 -> settled
  1, // 2 -> reached
};

const std::string& Expansion_EdgeStatus_Name(
    Expansion_EdgeStatus value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          Expansion_EdgeStatus_entries,
          Expansion_EdgeStatus_entries_by_number,
          3, Expansion_EdgeStatus_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      Expansion_EdgeStatus_entries,
      Expansion_EdgeStatus_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     Expansion_EdgeStatus_strings[idx].get();
}
bool Expansion_EdgeStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Expansion_EdgeStatus* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      Expansion_EdgeStatus_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<Expansion_EdgeStatus>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Expansion_EdgeStatus Expansion::connected;
constexpr Expansion_EdgeStatus Expansion::settled;
constexpr Expansion_EdgeStatus Expansion::reached;
constexpr Expansion_EdgeStatus Expansion::EdgeStatus_MIN;
constexpr Expansion_EdgeStatus Expansion::EdgeStatus_MAX;
constexpr int Expansion::EdgeStatus_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool Expansion_ExpansionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> Expansion_ExpansionType_strings[2] = {};

static const char Expansion_ExpansionType_names[] =
  "forward"
  "reverse";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry Expansion_ExpansionType_entries[] = {
  { {Expansion_ExpansionType_names + 0, 7}, 0 },
  { {Expansion_ExpansionType_names + 7, 7}, 1 },
};

static const int Expansion_ExpansionType_entries_by_number[] = {
  0, // 0 -> forward
  1, // 1 -> reverse
};

const std::string& Expansion_ExpansionType_Name(
    Expansion_ExpansionType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          Expansion_ExpansionType_entries,
          Expansion_ExpansionType_entries_by_number,
          2, Expansion_ExpansionType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      Expansion_ExpansionType_entries,
      Expansion_ExpansionType_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     Expansion_ExpansionType_strings[idx].get();
}
bool Expansion_ExpansionType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Expansion_ExpansionType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      Expansion_ExpansionType_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<Expansion_ExpansionType>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Expansion_ExpansionType Expansion::forward;
constexpr Expansion_ExpansionType Expansion::reverse;
constexpr Expansion_ExpansionType Expansion::ExpansionType_MIN;
constexpr Expansion_ExpansionType Expansion::ExpansionType_MAX;
constexpr int Expansion::ExpansionType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Expansion_Geometry::_Internal {
 public:
};

Expansion_Geometry::Expansion_Geometry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  coords_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:valhalla.Expansion.Geometry)
}
Expansion_Geometry::Expansion_Geometry(const Expansion_Geometry& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      coords_(from.coords_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:valhalla.Expansion.Geometry)
}

inline void Expansion_Geometry::SharedCtor() {
}

Expansion_Geometry::~Expansion_Geometry() {
  // @@protoc_insertion_point(destructor:valhalla.Expansion.Geometry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Expansion_Geometry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Expansion_Geometry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Expansion_Geometry::Clear() {
// @@protoc_insertion_point(message_clear_start:valhalla.Expansion.Geometry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  coords_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Expansion_Geometry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated sint32 coords = 1 [packed = true];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedSInt32Parser(_internal_mutable_coords(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_coords(::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Expansion_Geometry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:valhalla.Expansion.Geometry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated sint32 coords = 1 [packed = true];
  {
    int byte_size = _coords_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteSInt32Packed(
          1, _internal_coords(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:valhalla.Expansion.Geometry)
  return target;
}

size_t Expansion_Geometry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:valhalla.Expansion.Geometry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated sint32 coords = 1 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      SInt32Size(this->coords_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _coords_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Expansion_Geometry::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Expansion_Geometry*>(
      &from));
}

void Expansion_Geometry::MergeFrom(const Expansion_Geometry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:valhalla.Expansion.Geometry)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  coords_.MergeFrom(from.coords_);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Expansion_Geometry::CopyFrom(const Expansion_Geometry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:valhalla.Expansion.Geometry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Expansion_Geometry::IsInitialized() const {
  return true;
}

void Expansion_Geometry::InternalSwap(Expansion_Geometry* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  coords_.InternalSwap(&other->coords_);
}

std::string Expansion_Geometry::GetTypeName() const {
  return "valhalla.Expansion.Geometry";
}


// ===================================================================

class Expansion::_Internal {
 public:
};

Expansion::Expansion(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  costs_(arena),
  durations_(arena),
  distances_(arena),
  edge_status_(arena),
  edge_id_(arena),
  pred_edge_id_(arena),
  geometries_(arena),
  expansion_type_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:valhalla.Expansion)
}
Expansion::Expansion(const Expansion& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      costs_(from.costs_),
      durations_(from.durations_),
      distances_(from.distances_),
      edge_status_(from.edge_status_),
      edge_id_(from.edge_id_),
      pred_edge_id_(from.pred_edge_id_),
      geometries_(from.geometries_),
      expansion_type_(from.expansion_type_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:valhalla.Expansion)
}

inline void Expansion::SharedCtor() {
}

Expansion::~Expansion() {
  // @@protoc_insertion_point(destructor:valhalla.Expansion)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Expansion::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Expansion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Expansion::Clear() {
// @@protoc_insertion_point(message_clear_start:valhalla.Expansion)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  costs_.Clear();
  durations_.Clear();
  distances_.Clear();
  edge_status_.Clear();
  edge_id_.Clear();
  pred_edge_id_.Clear();
  geometries_.Clear();
  expansion_type_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Expansion::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated uint32 costs = 1 [packed = true];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_costs(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_costs(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 durations = 2 [packed = true];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_durations(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_durations(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 distances = 3 [packed = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_distances(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 24) {
          _internal_add_distances(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .valhalla.Expansion.EdgeStatus edge_status = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_edge_status(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_edge_status(static_cast<::valhalla::Expansion_EdgeStatus>(val));
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 edge_id = 5 [packed = true];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_edge_id(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 40) {
          _internal_add_edge_id(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 pred_edge_id = 6 [packed = true];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_pred_edge_id(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 48) {
          _internal_add_pred_edge_id(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .valhalla.Expansion.Geometry geometries = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_geometries(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .valhalla.Expansion.ExpansionType expansion_type = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_expansion_type(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 64) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_expansion_type(static_cast<::valhalla::Expansion_ExpansionType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Expansion::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:valhalla.Expansion)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 costs = 1 [packed = true];
  {
    int byte_size = _costs_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          1, _internal_costs(), byte_size, target);
    }
  }

  // repeated uint32 durations = 2 [packed = true];
  {
    int byte_size = _durations_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          2, _internal_durations(), byte_size, target);
    }
  }

  // repeated uint32 distances = 3 [packed = true];
  {
    int byte_size = _distances_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          3, _internal_distances(), byte_size, target);
    }
  }

  // repeated .valhalla.Expansion.EdgeStatus edge_status = 4;
  {
    int byte_size = _edge_status_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          4, edge_status_, byte_size, target);
    }
  }

  // repeated uint32 edge_id = 5 [packed = true];
  {
    int byte_size = _edge_id_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          5, _internal_edge_id(), byte_size, target);
    }
  }

  // repeated uint32 pred_edge_id = 6 [packed = true];
  {
    int byte_size = _pred_edge_id_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          6, _internal_pred_edge_id(), byte_size, target);
    }
  }

  // repeated .valhalla.Expansion.Geometry geometries = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_geometries_size()); i < n; i++) {
    const auto& repfield = this->_internal_geometries(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .valhalla.Expansion.ExpansionType expansion_type = 8;
  {
    int byte_size = _expansion_type_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          8, expansion_type_, byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:valhalla.Expansion)
  return target;
}

size_t Expansion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:valhalla.Expansion)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 costs = 1 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->costs_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _costs_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated uint32 durations = 2 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->durations_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _durations_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated uint32 distances = 3 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->distances_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _distances_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .valhalla.Expansion.EdgeStatus edge_status = 4;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_edge_status_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::_pbi::WireFormatLite::EnumSize(
        this->_internal_edge_status(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _edge_status_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated uint32 edge_id = 5 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->edge_id_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _edge_id_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated uint32 pred_edge_id = 6 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->pred_edge_id_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _pred_edge_id_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .valhalla.Expansion.Geometry geometries = 7;
  total_size += 1UL * this->_internal_geometries_size();
  for (const auto& msg : this->geometries_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .valhalla.Expansion.ExpansionType expansion_type = 8;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_expansion_type_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::_pbi::WireFormatLite::EnumSize(
        this->_internal_expansion_type(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _expansion_type_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Expansion::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Expansion*>(
      &from));
}

void Expansion::MergeFrom(const Expansion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:valhalla.Expansion)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  costs_.MergeFrom(from.costs_);
  durations_.MergeFrom(from.durations_);
  distances_.MergeFrom(from.distances_);
  edge_status_.MergeFrom(from.edge_status_);
  edge_id_.MergeFrom(from.edge_id_);
  pred_edge_id_.MergeFrom(from.pred_edge_id_);
  geometries_.MergeFrom(from.geometries_);
  expansion_type_.MergeFrom(from.expansion_type_);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Expansion::CopyFrom(const Expansion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:valhalla.Expansion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Expansion::IsInitialized() const {
  return true;
}

void Expansion::InternalSwap(Expansion* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  costs_.InternalSwap(&other->costs_);
  durations_.InternalSwap(&other->durations_);
  distances_.InternalSwap(&other->distances_);
  edge_status_.InternalSwap(&other->edge_status_);
  edge_id_.InternalSwap(&other->edge_id_);
  pred_edge_id_.InternalSwap(&other->pred_edge_id_);
  geometries_.InternalSwap(&other->geometries_);
  expansion_type_.InternalSwap(&other->expansion_type_);
}

std::string Expansion::GetTypeName() const {
  return "valhalla.Expansion";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace valhalla
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::valhalla::Expansion_Geometry*
Arena::CreateMaybeMessage< ::valhalla::Expansion_Geometry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::valhalla::Expansion_Geometry >(arena);
}
template<> PROTOBUF_NOINLINE ::valhalla::Expansion*
Arena::CreateMaybeMessage< ::valhalla::Expansion >(Arena* arena) {
  return Arena::CreateMessageInternal< ::valhalla::Expansion >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
