// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: isochrone.proto

#include "isochrone.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace valhalla {
PROTOBUF_CONSTEXPR Isochrone_Geometry::Isochrone_Geometry(
    ::_pbi::ConstantInitialized)
  : coords_()
  , _coords_cached_byte_size_(0){}
struct Isochrone_GeometryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Isochrone_GeometryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Isochrone_GeometryDefaultTypeInternal() {}
  union {
    Isochrone_Geometry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Isochrone_GeometryDefaultTypeInternal _Isochrone_Geometry_default_instance_;
PROTOBUF_CONSTEXPR Isochrone_Contour::Isochrone_Contour(
    ::_pbi::ConstantInitialized)
  : geometries_(){}
struct Isochrone_ContourDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Isochrone_ContourDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Isochrone_ContourDefaultTypeInternal() {}
  union {
    Isochrone_Contour _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Isochrone_ContourDefaultTypeInternal _Isochrone_Contour_default_instance_;
PROTOBUF_CONSTEXPR Isochrone_Interval::Isochrone_Interval(
    ::_pbi::ConstantInitialized)
  : contours_()
  , metric_(0)

  , metric_value_(0){}
struct Isochrone_IntervalDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Isochrone_IntervalDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Isochrone_IntervalDefaultTypeInternal() {}
  union {
    Isochrone_Interval _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Isochrone_IntervalDefaultTypeInternal _Isochrone_Interval_default_instance_;
PROTOBUF_CONSTEXPR Isochrone::Isochrone(
    ::_pbi::ConstantInitialized)
  : intervals_(){}
struct IsochroneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IsochroneDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IsochroneDefaultTypeInternal() {}
  union {
    Isochrone _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IsochroneDefaultTypeInternal _Isochrone_default_instance_;
}  // namespace valhalla
namespace valhalla {
bool Isochrone_metric_type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> Isochrone_metric_type_strings[2] = {};

static const char Isochrone_metric_type_names[] =
  "distance"
  "time";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry Isochrone_metric_type_entries[] = {
  { {Isochrone_metric_type_names + 0, 8}, 1 },
  { {Isochrone_metric_type_names + 8, 4}, 0 },
};

static const int Isochrone_metric_type_entries_by_number[] = {
  1, // 0 -> time
  0, // 1 -> distance
};

const std::string& Isochrone_metric_type_Name(
    Isochrone_metric_type value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          Isochrone_metric_type_entries,
          Isochrone_metric_type_entries_by_number,
          2, Isochrone_metric_type_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      Isochrone_metric_type_entries,
      Isochrone_metric_type_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     Isochrone_metric_type_strings[idx].get();
}
bool Isochrone_metric_type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Isochrone_metric_type* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      Isochrone_metric_type_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<Isochrone_metric_type>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Isochrone_metric_type Isochrone::time;
constexpr Isochrone_metric_type Isochrone::distance;
constexpr Isochrone_metric_type Isochrone::metric_type_MIN;
constexpr Isochrone_metric_type Isochrone::metric_type_MAX;
constexpr int Isochrone::metric_type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Isochrone_Geometry::_Internal {
 public:
};

Isochrone_Geometry::Isochrone_Geometry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  coords_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:valhalla.Isochrone.Geometry)
}
Isochrone_Geometry::Isochrone_Geometry(const Isochrone_Geometry& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      coords_(from.coords_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:valhalla.Isochrone.Geometry)
}

inline void Isochrone_Geometry::SharedCtor() {
}

Isochrone_Geometry::~Isochrone_Geometry() {
  // @@protoc_insertion_point(destructor:valhalla.Isochrone.Geometry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Isochrone_Geometry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Isochrone_Geometry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Isochrone_Geometry::Clear() {
// @@protoc_insertion_point(message_clear_start:valhalla.Isochrone.Geometry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  coords_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Isochrone_Geometry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated sint32 coords = 1 [packed = true];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedSInt32Parser(_internal_mutable_coords(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_coords(::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Isochrone_Geometry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:valhalla.Isochrone.Geometry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated sint32 coords = 1 [packed = true];
  {
    int byte_size = _coords_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteSInt32Packed(
          1, _internal_coords(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:valhalla.Isochrone.Geometry)
  return target;
}

size_t Isochrone_Geometry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:valhalla.Isochrone.Geometry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated sint32 coords = 1 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      SInt32Size(this->coords_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _coords_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Isochrone_Geometry::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Isochrone_Geometry*>(
      &from));
}

void Isochrone_Geometry::MergeFrom(const Isochrone_Geometry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:valhalla.Isochrone.Geometry)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  coords_.MergeFrom(from.coords_);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Isochrone_Geometry::CopyFrom(const Isochrone_Geometry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:valhalla.Isochrone.Geometry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Isochrone_Geometry::IsInitialized() const {
  return true;
}

void Isochrone_Geometry::InternalSwap(Isochrone_Geometry* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  coords_.InternalSwap(&other->coords_);
}

std::string Isochrone_Geometry::GetTypeName() const {
  return "valhalla.Isochrone.Geometry";
}


// ===================================================================

class Isochrone_Contour::_Internal {
 public:
};

Isochrone_Contour::Isochrone_Contour(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  geometries_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:valhalla.Isochrone.Contour)
}
Isochrone_Contour::Isochrone_Contour(const Isochrone_Contour& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      geometries_(from.geometries_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:valhalla.Isochrone.Contour)
}

inline void Isochrone_Contour::SharedCtor() {
}

Isochrone_Contour::~Isochrone_Contour() {
  // @@protoc_insertion_point(destructor:valhalla.Isochrone.Contour)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Isochrone_Contour::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Isochrone_Contour::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Isochrone_Contour::Clear() {
// @@protoc_insertion_point(message_clear_start:valhalla.Isochrone.Contour)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  geometries_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Isochrone_Contour::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .valhalla.Isochrone.Geometry geometries = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_geometries(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Isochrone_Contour::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:valhalla.Isochrone.Contour)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .valhalla.Isochrone.Geometry geometries = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_geometries_size()); i < n; i++) {
    const auto& repfield = this->_internal_geometries(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:valhalla.Isochrone.Contour)
  return target;
}

size_t Isochrone_Contour::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:valhalla.Isochrone.Contour)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .valhalla.Isochrone.Geometry geometries = 2;
  total_size += 1UL * this->_internal_geometries_size();
  for (const auto& msg : this->geometries_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Isochrone_Contour::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Isochrone_Contour*>(
      &from));
}

void Isochrone_Contour::MergeFrom(const Isochrone_Contour& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:valhalla.Isochrone.Contour)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  geometries_.MergeFrom(from.geometries_);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Isochrone_Contour::CopyFrom(const Isochrone_Contour& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:valhalla.Isochrone.Contour)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Isochrone_Contour::IsInitialized() const {
  return true;
}

void Isochrone_Contour::InternalSwap(Isochrone_Contour* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  geometries_.InternalSwap(&other->geometries_);
}

std::string Isochrone_Contour::GetTypeName() const {
  return "valhalla.Isochrone.Contour";
}


// ===================================================================

class Isochrone_Interval::_Internal {
 public:
};

Isochrone_Interval::Isochrone_Interval(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  contours_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:valhalla.Isochrone.Interval)
}
Isochrone_Interval::Isochrone_Interval(const Isochrone_Interval& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      contours_(from.contours_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&metric_, &from.metric_,
    static_cast<size_t>(reinterpret_cast<char*>(&metric_value_) -
    reinterpret_cast<char*>(&metric_)) + sizeof(metric_value_));
  // @@protoc_insertion_point(copy_constructor:valhalla.Isochrone.Interval)
}

inline void Isochrone_Interval::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&metric_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&metric_value_) -
    reinterpret_cast<char*>(&metric_)) + sizeof(metric_value_));
}

Isochrone_Interval::~Isochrone_Interval() {
  // @@protoc_insertion_point(destructor:valhalla.Isochrone.Interval)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Isochrone_Interval::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Isochrone_Interval::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Isochrone_Interval::Clear() {
// @@protoc_insertion_point(message_clear_start:valhalla.Isochrone.Interval)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  contours_.Clear();
  ::memset(&metric_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&metric_value_) -
      reinterpret_cast<char*>(&metric_)) + sizeof(metric_value_));
  _internal_metadata_.Clear<std::string>();
}

const char* Isochrone_Interval::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .valhalla.Isochrone.metric_type metric = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_metric(static_cast<::valhalla::Isochrone_metric_type>(val));
        } else
          goto handle_unusual;
        continue;
      // float metric_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          metric_value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated .valhalla.Isochrone.Contour contours = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_contours(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Isochrone_Interval::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:valhalla.Isochrone.Interval)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .valhalla.Isochrone.metric_type metric = 1;
  if (this->_internal_metric() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_metric(), target);
  }

  // float metric_value = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_metric_value = this->_internal_metric_value();
  uint32_t raw_metric_value;
  memcpy(&raw_metric_value, &tmp_metric_value, sizeof(tmp_metric_value));
  if (raw_metric_value != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_metric_value(), target);
  }

  // repeated .valhalla.Isochrone.Contour contours = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_contours_size()); i < n; i++) {
    const auto& repfield = this->_internal_contours(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:valhalla.Isochrone.Interval)
  return target;
}

size_t Isochrone_Interval::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:valhalla.Isochrone.Interval)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .valhalla.Isochrone.Contour contours = 3;
  total_size += 1UL * this->_internal_contours_size();
  for (const auto& msg : this->contours_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .valhalla.Isochrone.metric_type metric = 1;
  if (this->_internal_metric() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_metric());
  }

  // float metric_value = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_metric_value = this->_internal_metric_value();
  uint32_t raw_metric_value;
  memcpy(&raw_metric_value, &tmp_metric_value, sizeof(tmp_metric_value));
  if (raw_metric_value != 0) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Isochrone_Interval::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Isochrone_Interval*>(
      &from));
}

void Isochrone_Interval::MergeFrom(const Isochrone_Interval& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:valhalla.Isochrone.Interval)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  contours_.MergeFrom(from.contours_);
  if (from._internal_metric() != 0) {
    _internal_set_metric(from._internal_metric());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_metric_value = from._internal_metric_value();
  uint32_t raw_metric_value;
  memcpy(&raw_metric_value, &tmp_metric_value, sizeof(tmp_metric_value));
  if (raw_metric_value != 0) {
    _internal_set_metric_value(from._internal_metric_value());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Isochrone_Interval::CopyFrom(const Isochrone_Interval& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:valhalla.Isochrone.Interval)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Isochrone_Interval::IsInitialized() const {
  return true;
}

void Isochrone_Interval::InternalSwap(Isochrone_Interval* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  contours_.InternalSwap(&other->contours_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Isochrone_Interval, metric_value_)
      + sizeof(Isochrone_Interval::metric_value_)
      - PROTOBUF_FIELD_OFFSET(Isochrone_Interval, metric_)>(
          reinterpret_cast<char*>(&metric_),
          reinterpret_cast<char*>(&other->metric_));
}

std::string Isochrone_Interval::GetTypeName() const {
  return "valhalla.Isochrone.Interval";
}


// ===================================================================

class Isochrone::_Internal {
 public:
};

Isochrone::Isochrone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  intervals_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:valhalla.Isochrone)
}
Isochrone::Isochrone(const Isochrone& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      intervals_(from.intervals_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:valhalla.Isochrone)
}

inline void Isochrone::SharedCtor() {
}

Isochrone::~Isochrone() {
  // @@protoc_insertion_point(destructor:valhalla.Isochrone)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Isochrone::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Isochrone::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Isochrone::Clear() {
// @@protoc_insertion_point(message_clear_start:valhalla.Isochrone)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  intervals_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Isochrone::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .valhalla.Isochrone.Interval intervals = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_intervals(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Isochrone::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:valhalla.Isochrone)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .valhalla.Isochrone.Interval intervals = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_intervals_size()); i < n; i++) {
    const auto& repfield = this->_internal_intervals(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:valhalla.Isochrone)
  return target;
}

size_t Isochrone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:valhalla.Isochrone)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .valhalla.Isochrone.Interval intervals = 1;
  total_size += 1UL * this->_internal_intervals_size();
  for (const auto& msg : this->intervals_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Isochrone::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Isochrone*>(
      &from));
}

void Isochrone::MergeFrom(const Isochrone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:valhalla.Isochrone)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  intervals_.MergeFrom(from.intervals_);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Isochrone::CopyFrom(const Isochrone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:valhalla.Isochrone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Isochrone::IsInitialized() const {
  return true;
}

void Isochrone::InternalSwap(Isochrone* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  intervals_.InternalSwap(&other->intervals_);
}

std::string Isochrone::GetTypeName() const {
  return "valhalla.Isochrone";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace valhalla
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::valhalla::Isochrone_Geometry*
Arena::CreateMaybeMessage< ::valhalla::Isochrone_Geometry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::valhalla::Isochrone_Geometry >(arena);
}
template<> PROTOBUF_NOINLINE ::valhalla::Isochrone_Contour*
Arena::CreateMaybeMessage< ::valhalla::Isochrone_Contour >(Arena* arena) {
  return Arena::CreateMessageInternal< ::valhalla::Isochrone_Contour >(arena);
}
template<> PROTOBUF_NOINLINE ::valhalla::Isochrone_Interval*
Arena::CreateMaybeMessage< ::valhalla::Isochrone_Interval >(Arena* arena) {
  return Arena::CreateMessageInternal< ::valhalla::Isochrone_Interval >(arena);
}
template<> PROTOBUF_NOINLINE ::valhalla::Isochrone*
Arena::CreateMaybeMessage< ::valhalla::Isochrone >(Arena* arena) {
  return Arena::CreateMessageInternal< ::valhalla::Isochrone >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
