// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

#include "matrix.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace valhalla {
PROTOBUF_CONSTEXPR Matrix::Matrix(
    ::_pbi::ConstantInitialized)
  : distances_()
  , _distances_cached_byte_size_(0)
  , times_()
  , from_indices_()
  , _from_indices_cached_byte_size_(0)
  , to_indices_()
  , _to_indices_cached_byte_size_(0)
  , date_times_()
  , shapes_()
  , time_zone_offsets_()
  , time_zone_names_()
  , second_pass_()
  , algorithm_(0)
{}
struct MatrixDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MatrixDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MatrixDefaultTypeInternal() {}
  union {
    Matrix _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MatrixDefaultTypeInternal _Matrix_default_instance_;
}  // namespace valhalla
namespace valhalla {
bool Matrix_Algorithm_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> Matrix_Algorithm_strings[3] = {};

static const char Matrix_Algorithm_names[] =
  "CostMatrix"
  "TimeDistanceBSSMatrix"
  "TimeDistanceMatrix";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry Matrix_Algorithm_entries[] = {
  { {Matrix_Algorithm_names + 0, 10}, 1 },
  { {Matrix_Algorithm_names + 10, 21}, 2 },
  { {Matrix_Algorithm_names + 31, 18}, 0 },
};

static const int Matrix_Algorithm_entries_by_number[] = {
  2, // 0 -> TimeDistanceMatrix
  0, // 1 -> CostMatrix
  1, // 2 -> TimeDistanceBSSMatrix
};

const std::string& Matrix_Algorithm_Name(
    Matrix_Algorithm value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          Matrix_Algorithm_entries,
          Matrix_Algorithm_entries_by_number,
          3, Matrix_Algorithm_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      Matrix_Algorithm_entries,
      Matrix_Algorithm_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     Matrix_Algorithm_strings[idx].get();
}
bool Matrix_Algorithm_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Matrix_Algorithm* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      Matrix_Algorithm_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<Matrix_Algorithm>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Matrix_Algorithm Matrix::TimeDistanceMatrix;
constexpr Matrix_Algorithm Matrix::CostMatrix;
constexpr Matrix_Algorithm Matrix::TimeDistanceBSSMatrix;
constexpr Matrix_Algorithm Matrix::Algorithm_MIN;
constexpr Matrix_Algorithm Matrix::Algorithm_MAX;
constexpr int Matrix::Algorithm_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Matrix::_Internal {
 public:
};

Matrix::Matrix(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  distances_(arena),
  times_(arena),
  from_indices_(arena),
  to_indices_(arena),
  date_times_(arena),
  shapes_(arena),
  time_zone_offsets_(arena),
  time_zone_names_(arena),
  second_pass_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:valhalla.Matrix)
}
Matrix::Matrix(const Matrix& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      distances_(from.distances_),
      times_(from.times_),
      from_indices_(from.from_indices_),
      to_indices_(from.to_indices_),
      date_times_(from.date_times_),
      shapes_(from.shapes_),
      time_zone_offsets_(from.time_zone_offsets_),
      time_zone_names_(from.time_zone_names_),
      second_pass_(from.second_pass_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  algorithm_ = from.algorithm_;
  // @@protoc_insertion_point(copy_constructor:valhalla.Matrix)
}

inline void Matrix::SharedCtor() {
algorithm_ = 0;
}

Matrix::~Matrix() {
  // @@protoc_insertion_point(destructor:valhalla.Matrix)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Matrix::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Matrix::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Matrix::Clear() {
// @@protoc_insertion_point(message_clear_start:valhalla.Matrix)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  distances_.Clear();
  times_.Clear();
  from_indices_.Clear();
  to_indices_.Clear();
  date_times_.Clear();
  shapes_.Clear();
  time_zone_offsets_.Clear();
  time_zone_names_.Clear();
  second_pass_.Clear();
  algorithm_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* Matrix::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated uint32 distances = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_distances(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_distances(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float times = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_times(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 29) {
          _internal_add_times(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 from_indices = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_from_indices(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_from_indices(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 to_indices = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_to_indices(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 40) {
          _internal_add_to_indices(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string date_times = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_date_times();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, nullptr));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .valhalla.Matrix.Algorithm algorithm = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_algorithm(static_cast<::valhalla::Matrix_Algorithm>(val));
        } else
          goto handle_unusual;
        continue;
      // repeated string shapes = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_shapes();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, nullptr));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string time_zone_offsets = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_time_zone_offsets();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, nullptr));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string time_zone_names = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_time_zone_names();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, nullptr));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<82>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated bool second_pass = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedBoolParser(_internal_mutable_second_pass(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 88) {
          _internal_add_second_pass(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Matrix::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:valhalla.Matrix)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 distances = 2;
  {
    int byte_size = _distances_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          2, _internal_distances(), byte_size, target);
    }
  }

  // repeated float times = 3;
  if (this->_internal_times_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_times(), target);
  }

  // repeated uint32 from_indices = 4;
  {
    int byte_size = _from_indices_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          4, _internal_from_indices(), byte_size, target);
    }
  }

  // repeated uint32 to_indices = 5;
  {
    int byte_size = _to_indices_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          5, _internal_to_indices(), byte_size, target);
    }
  }

  // repeated string date_times = 6;
  for (int i = 0, n = this->_internal_date_times_size(); i < n; i++) {
    const auto& s = this->_internal_date_times(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "valhalla.Matrix.date_times");
    target = stream->WriteString(6, s, target);
  }

  // .valhalla.Matrix.Algorithm algorithm = 7;
  if (this->_internal_algorithm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      7, this->_internal_algorithm(), target);
  }

  // repeated string shapes = 8;
  for (int i = 0, n = this->_internal_shapes_size(); i < n; i++) {
    const auto& s = this->_internal_shapes(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "valhalla.Matrix.shapes");
    target = stream->WriteString(8, s, target);
  }

  // repeated string time_zone_offsets = 9;
  for (int i = 0, n = this->_internal_time_zone_offsets_size(); i < n; i++) {
    const auto& s = this->_internal_time_zone_offsets(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "valhalla.Matrix.time_zone_offsets");
    target = stream->WriteString(9, s, target);
  }

  // repeated string time_zone_names = 10;
  for (int i = 0, n = this->_internal_time_zone_names_size(); i < n; i++) {
    const auto& s = this->_internal_time_zone_names(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "valhalla.Matrix.time_zone_names");
    target = stream->WriteString(10, s, target);
  }

  // repeated bool second_pass = 11;
  if (this->_internal_second_pass_size() > 0) {
    target = stream->WriteFixedPacked(11, _internal_second_pass(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:valhalla.Matrix)
  return target;
}

size_t Matrix::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:valhalla.Matrix)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 distances = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->distances_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _distances_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float times = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_times_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated uint32 from_indices = 4;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->from_indices_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _from_indices_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated uint32 to_indices = 5;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->to_indices_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _to_indices_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated string date_times = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(date_times_.size());
  for (int i = 0, n = date_times_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      date_times_.Get(i));
  }

  // repeated string shapes = 8;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(shapes_.size());
  for (int i = 0, n = shapes_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      shapes_.Get(i));
  }

  // repeated string time_zone_offsets = 9;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(time_zone_offsets_.size());
  for (int i = 0, n = time_zone_offsets_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      time_zone_offsets_.Get(i));
  }

  // repeated string time_zone_names = 10;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(time_zone_names_.size());
  for (int i = 0, n = time_zone_names_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      time_zone_names_.Get(i));
  }

  // repeated bool second_pass = 11;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_second_pass_size());
    size_t data_size = 1UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // .valhalla.Matrix.Algorithm algorithm = 7;
  if (this->_internal_algorithm() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_algorithm());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Matrix::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Matrix*>(
      &from));
}

void Matrix::MergeFrom(const Matrix& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:valhalla.Matrix)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  distances_.MergeFrom(from.distances_);
  times_.MergeFrom(from.times_);
  from_indices_.MergeFrom(from.from_indices_);
  to_indices_.MergeFrom(from.to_indices_);
  date_times_.MergeFrom(from.date_times_);
  shapes_.MergeFrom(from.shapes_);
  time_zone_offsets_.MergeFrom(from.time_zone_offsets_);
  time_zone_names_.MergeFrom(from.time_zone_names_);
  second_pass_.MergeFrom(from.second_pass_);
  if (from._internal_algorithm() != 0) {
    _internal_set_algorithm(from._internal_algorithm());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Matrix::CopyFrom(const Matrix& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:valhalla.Matrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Matrix::IsInitialized() const {
  return true;
}

void Matrix::InternalSwap(Matrix* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  distances_.InternalSwap(&other->distances_);
  times_.InternalSwap(&other->times_);
  from_indices_.InternalSwap(&other->from_indices_);
  to_indices_.InternalSwap(&other->to_indices_);
  date_times_.InternalSwap(&other->date_times_);
  shapes_.InternalSwap(&other->shapes_);
  time_zone_offsets_.InternalSwap(&other->time_zone_offsets_);
  time_zone_names_.InternalSwap(&other->time_zone_names_);
  second_pass_.InternalSwap(&other->second_pass_);
  swap(algorithm_, other->algorithm_);
}

std::string Matrix::GetTypeName() const {
  return "valhalla.Matrix";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace valhalla
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::valhalla::Matrix*
Arena::CreateMaybeMessage< ::valhalla::Matrix >(Arena* arena) {
  return Arena::CreateMessageInternal< ::valhalla::Matrix >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
